### ISSUE TITLE
Tooltip missmatch

### ISSUE THREAD

**Issue by dropbear-github** [BattletechModders/LowVisibility#2]
The "Vision and Sensor" tooltip in game and the actual calulations for the sensorcheck multiplier don't match. 
`
UIPatches.BuildToolTip 
`
shows:  
`
 float rangeMulti = 1.0f + ((ewState.rangeCheck + ewState.SensorCheckModifier()) / 10.0f); 
`
while the calculation in 
`
EWState.SensorCheckModifier
`
 is 
`
 return 1.0f + ((rangeCheck + SensorCheckModifier()) / 20.0f);
`

**Comment by IceRaptor** [comment]
Fixed in 0.6.1
