### ISSUE TITLE
Can't load the mod

### ISSUE THREAD

**Issue by drugonam** [BattletechModders/LowVisibility#56]
For some reason I'm getting an error trying to load Low Visibility. I thought that the problem can be in IRBTModUtils-1.7.0 but installing it haven't solved the problem. Should I upload ModTek.log somewhere?

**Comment by IceRaptor** [comment]
@drugonam sorry, the fault is likely mine. I need to update the mod description - it now requires several other mods to work properly. These include MechEngineer (ME), CAC (CustomAmmoCategories), CAE (Custom Aura),  and CustomComponents (CC). If you have all of those and are still having issues, attach the ModTek.log, lowVisibility.log, and cleaned_output.log and I'll try to help!

**Comment by drugonam** [comment]
Ah I see. Could you tell me where should I get them? I tried the following pack but it doesn't load custom mods for some reason.
https://www.nexusmods.com/battletech/mods/381
I'm trying to run Low Visibility with BattleTech Extended.

**Comment by IceRaptor** [comment]
If you're still interested in trying this, you can get the other mods from https://github.com/battletechmodders/custombundle/. However, because you're trying to use the mods with BEX I'd strongly recommend you check out the #other-mods channel on the BEX discord (https://discord.gg/6FTzR7fh - should be good for 7 days). I know for a fact that several folks there are running LowVis with BEX and they should be able to help you out.

**Comment by drugonam** [comment]
Hello.
 
Just tried it again first with BEX and then without it. I downloaded latest version of CAB, ModTek, IRBTModUtils and Custom Bundle (took only CAE and CAC from it). So I can’t run Low Visibility even without any other mod.
  
> 
>If you're still interested in trying this, you can get the other mods from  https://github.com/battletechmodders/custombundle/ . However, because you're trying to use the mods with BEX I'd strongly recommend you check out the #other-mods channel on the BEX discord ( https://discord.gg/6FTzR7fh - should be good for 7 days). I know for a fact that several folks there are running LowVis with BEX and they should be able to help you out.
