### ISSUE TITLE
Enemies don't shoot on first turn

### ISSUE THREAD

**Issue by CargoVroom** [BattletechModders/LowVisibility#6]
This may or may not be a LowVis issue. But has been observed in BT 1.6 running the RT Patch 12 alphas and seems like a problem with detection checks.

Enemies do not fire on their first turn. This is easily observable when they are dropped mid-contract but may also affect ones that are spawned at start.

They move, but don't ever shoot on their first turn.
Their movement choices seem odd, as if they are blind to the player, often running past player units and turning their backs.

**Comment by IceRaptor** [comment]
No longer seems to be the case.
