### ISSUE TITLE
ECM Signature Modifier Behavior does not match readme

### ISSUE THREAD

**Issue by DrBwaa** [BattletechModders/LowVisibility#61]
The readme indicates that each point of ECM shield on a unit decreases its signature by 5%, but the code seems to _increase_ the unit's signature by 10% per point instead.

https://github.com/BattletechModders/LowVisibility/blob/80bd58ec0a656eec83355377ed35db89dceb543c/LowVisibility/LowVisibility/Object/EWState.cs#L373

If this were being used as a signature decrease, I would expect a negative multiplier (-0.05 would be the value indicated in the readme).

**Comment by IceRaptor** [comment]
Fixed in 1.0
